version: '3.8'

<<<<<<< HEAD
services:
  mysqldb:
    image: mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
=======
services: 
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=api-product-category
>>>>>>> 11cefaea9cbd7d92b98d56feeb632d9ac435a34c
    ports:
      - "3307:3306"