version: '3'

services:
  web-development:
    build:
      context: .
      target: development
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app

  web-production:
    build:
      context: .
      target: production
    ports:
      - "80:80"
