version: '3.8'
services:
  mysql: 
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always 
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 8081:80
    depends_on:
      - mysql
  development:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    container_name: development
    restart: always
    volumes:
      - ./src:/usr/src/app/src
    ports: 
      - 3003:3000
    depends_on:
      - mysql
      - phpmyadmin
  production:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: production
    restart: always
    ports: 
      - 3004:3000
    depends_on:
      - mysql
      - phpmyadmin
