version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: producto-categoria
      
    ports:
      - 3306:3306
     volumes:
        - "./mysql2:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin3
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 8080:80
    depends_on:
      - db

  development:
    build:
      target: development
      context: .
    image: development
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ".:/usr/src/app"
    depends_on:
      - db
      - phpmyadmin

  production:
    build:
      target: production
      context: .
    image: production
    restart: always
    env_file:
      - .env
    ports:
      - '3001:3000'
    depends_on:
      - db
      - phpmyadmin