version: '3'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules